CREATE DATABASE IF NOT EXIST php;

USE php;

CREATE TABLE crud(
id INT AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(30) NOT NULL,
description VARCHAR(50) NOT NULL
);


CREATE USER 'User'@'localhost' IDENTIFIED BY '0000';

GRANT ALL ON php.* TO 'User'@'localhost';

FLUSH PRIVILEGES;

